### ISSUE TITLE
Small gap in multi-site setups in Drupal 10

### ISSUE THREAD

**Issue by philipnorton42** [codeenigma/ansible-deploy#448]
For multi-site setups, if the default.settings.php file isn't present in the same directory as the currently used settings.php file then the site will crash.

So, if we have a multi-site setup called `mysite` then the folder structure must look like this:

```
web/
   sites/
      mysite/
         default.settings.php
         settings.php
   sites.php
```

I think this must be a new thing as I can't recall seeing this issue before Drupal 10.

**Comment by gregharvey** [comment]
This is resolved now. :slightly_smiling_face:
